---
####################
# Install Keycloak
####################

- name: Generate deplyoment
  template:
    src: keycloak.yaml.j2
    dest: /tmp/keycloak.yaml
    mode: 0744
  become: false

# Deploy Keycloak

- name: Deploy Keycloak
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/keycloak.yaml"

- name: Verify that all pods are ready
  shell: kubectl --namespace {{ namespace }} get pods | grep "keycloak" | grep "Running" | wc -l
  register: cmd_result
  until: cmd_result.stdout.find('1') != -1
  retries: 20
  delay: 30