# The secrets should be base64 encoded
# apiVersion: v1
# kind: Secret
# metadata:
#   name: keycloak
#   labels:
#     app: keycloak
#     layer: auth
#     project: oidcprovider
# data:
#   admin_password: "{{ 'password' | b64encode }}"
#   postgres_password: "{{ 'password' | b64encode }}"

# ---
# # The secrets should be base64 encoded
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: keycloak
#   labels:
#     app: keycloak
#     layer: auth
#     project: oidcprovider
# data:
#   admin_user: "admin"
#   postgres_user: "postgres"
#   postgres_database: "keycloak"
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
    layer: auth
    project: oidcprovider
spec:
  replicas: 1
  template:
    metadata:
      name: keycloak
      labels:
        name: keycloak
        app: keycloak
        layer: auth
        project: oidcprovider
    spec:
      containers:
        - image: jboss/keycloak
          name: keycloak
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: password
            - name: POSTGRES_PASSWORD
              value: password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: postgres
          ports:
            - containerPort: 8080
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    layer: auth
    project: oidcprovider
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: keycloak
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  labels:
    app: keycloak
    layer: auth
    project: oidcprovider
spec:
  rules:
  - host: oidcprovider.35.226.212.121.nip.io
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 80